### ISSUE TITLE
Fix build process of base-ancestor

### ISSUE THREAD

**Issue by Niolon** [QCrBox/QCrBox#276]
Currently the build of base-ancestor fails. 

An easy fix seems to be to replace line 64 with: 
```
    ${MAMBA_EXE} install -y pip setuptools wheel conda-build && \
``` 

It needs to be checked whether that has implications down the line.

**Comment by maxalbert** [comment]
Huh, that's odd. That line was last modified in December 2023. I wonder what changed upstream that makes it fail now?

In any case, we can try removing the `build` package as per your suggestion above. If nothing breaks then great, otherwise we always install it separately via pip (instead of micromamba) in the Dockerfile. I'm testing the builds at the moment but it's taking a little while (if you have already tested this change then feel free to merge it).

**Comment by Niolon** [comment]
I have no idea, probably some requirements from other packages and/or build changed and are now conflicting. I successfully built all containers with this change. I was just not sure whether it was included for some edge case you encountered in the past.

**Comment by maxalbert** [comment]
IIRC I did include it on purpose at the time, but I think I was trying to debug build failures and wanted to rule out certain sources of errors so it's probably fine to remove it if things are working ok now (in any case, it is likely not needed inside the docker images).
